export const styles = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column' as const,
    backgroundColor: '#0f172a', // Fondo oscuro moderno (Slate 900)
    color: '#f8fafc',
    fontFamily: 'system-ui, -apple-system, sans-serif',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '20px 40px',
    borderBottom: '1px solid #1e293b',
    backgroundColor: '#0f172a',
  },
  logo: {
    fontSize: '24px',
    fontWeight: 'bold',
    cursor: 'pointer',
    color: '#38bdf8', // Azul cielo brillante
  },
  logoutBtn: {
    padding: '8px 16px',
    backgroundColor: '#ef4444',
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    fontWeight: 'bold' as const,
    cursor: 'pointer',
    transition: 'background 0.2s',
  },
  main: {
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '40px 20px',
  },
  // Estilos Landing
  landingWrapper: {
    textAlign: 'center' as const,
    maxWidth: '650px',
  },
  heroTitle: {
    fontSize: '48px',
    fontWeight: '800' as const,
    marginBottom: '20px',
    lineHeight: '1.2',
    backgroundImage: 'linear-gradient(to right, #38bdf8, #818cf8)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  heroSubtitle: {
    fontSize: '18px',
    color: '#94a3b8',
    lineHeight: '1.6',
    marginBottom: '35px',
  },
  btnGroup: {
    display: 'flex',
    justifyContent: 'center',
    gap: '20px',
  },
  primaryBtn: {
    padding: '14px 28px',
    backgroundColor: '#38bdf8',
    color: '#0f172a',
    border: 'none',
    borderRadius: '8px',
    fontSize: '16px',
    fontWeight: 'bold' as const,
    cursor: 'pointer',
    boxShadow: '0 4px 14px rgba(56, 189, 248, 0.3)',
  },
  secondaryBtn: {
    padding: '14px 28px',
    backgroundColor: 'transparent',
    color: '#f8fafc',
    border: '2px solid #334155',
    borderRadius: '8px',
    fontSize: '16px',
    fontWeight: 'bold' as const,
    cursor: 'pointer',
    transition: 'border 0.2s',
  },
  // Estilos Tarjeta (Login/Register)
  card: {
    backgroundColor: '#1e293b',
    padding: '40px',
    borderRadius: '16px',
    width: '100%',
    maxWidth: '450px',
    boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.3)',
    border: '1px solid #334155',
  },
  cardTitle: {
    fontSize: '28px',
    fontWeight: 'bold' as const,
    marginBottom: '8px',
    textAlign: 'center' as const,
  },
  cardSubtitle: {
    fontSize: '14px',
    color: '#94a3b8',
    textAlign: 'center' as const,
    marginBottom: '25px',
  },
  form: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '20px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  },
  label: {
    fontSize: '14px',
    color: '#cbd5e1',
    fontWeight: '500' as const,
  },
  input: {
    padding: '12px 16px',
    backgroundColor: '#0f172a',
    border: '1px solid #334155',
    borderRadius: '8px',
    color: '#fff',
    fontSize: '15px',
    outline: 'none',
  },
  submitBtn: {
    padding: '14px',
    backgroundColor: '#38bdf8',
    color: '#0f172a',
    border: 'none',
    borderRadius: '8px',
    fontSize: '16px',
    fontWeight: 'bold' as const,
    cursor: 'pointer',
    marginTop: '10px',
  },
  switchText: {
    fontSize: '14px',
    color: '#94a3b8',
    textAlign: 'center' as const,
    marginTop: '20px',
  },
  switchLink: {
    color: '#38bdf8',
    cursor: 'pointer',
    fontWeight: 'bold' as const,
  },
  successBox: {
    backgroundColor: '#065f46',
    color: '#34d399',
    padding: '12px',
    borderRadius: '8px',
    fontSize: '14px',
    marginBottom: '20px',
    textAlign: 'center' as const,
  },
  errorBox: {
    backgroundColor: '#7f1d1d',
    color: '#fca5a5',
    padding: '12px',
    borderRadius: '8px',
    fontSize: '14px',
    marginBottom: '20px',
    textAlign: 'center' as const,
  },
  // Estilos Dashboard
  dashboard: {
    width: '100%',
    maxWidth: '1000px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '30px',
  },
  welcomeBanner: {
    backgroundColor: '#1e293b',
    padding: '30px',
    borderRadius: '12px',
    borderLeft: '5px solid #38bdf8',
  },
  accentText: {
    color: '#38bdf8',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '24px',
  },
  dashboardCard: {
    backgroundColor: '#1e293b',
    padding: '24px',
    borderRadius: '12px',
    border: '1px solid #334155',
  },
  cardHeaderIcon: {
    fontSize: '32px',
    marginBottom: '12px',
  },
  metric: {
    fontSize: '28px',
    fontWeight: 'bold' as const,
    color: '#38bdf8',
    margin: '10px 0 5px 0',
  },
  metricSub: {
    fontSize: '12px',
    color: '#94a3b8',
  },
  // Agrega esto al final dentro del objeto existente en app_home/src/styles.ts
  budgetSection: {
    backgroundColor: '#1e293b',
    padding: '20px 30px',
    borderRadius: '12px',
    border: '1px solid #334155',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  budgetDisplayRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    flexWrap: 'wrap' as const,
    gap: '15px',
  },
  budgetEditRow: {
    display: 'flex',
    gap: '15px',
    width: '100%',
  },
  budgetLabel: {
    fontSize: '16px',
    color: '#94a3b8',
  },
  budgetValue: {
    fontSize: '24px',
    fontWeight: 'bold' as const,
    color: '#10b981', // Verde éxito para el dinero
    marginLeft: '10px',
  },
  inputBudget: {
    padding: '10px 16px',
    backgroundColor: '#0f172a',
    border: '1px solid #334155',
    borderRadius: '8px',
    color: '#fff',
    fontSize: '16px',
    flex: 1,
    outline: 'none',
  },
  editBudgetBtn: {
    padding: '10px 20px',
    backgroundColor: 'transparent',
    color: '#38bdf8',
    border: '1px solid #38bdf8',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 'bold' as const,
  },
  saveBudgetBtn: {
    padding: '10px 20px',
    backgroundColor: '#10b981',
    color: '#0f172a',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 'bold' as const,
  },
  cancelBudgetBtn: {
    padding: '10px 20px',
    backgroundColor: '#475569',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
  },
  suggestionsBox: {
    backgroundColor: '#1e293b',
    padding: '25px',
    borderRadius: '12px',
    border: '1px solid #334155',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '15px',
  },
  suggestionItem: {
    backgroundColor: '#0f172a',
    padding: '15px',
    borderRadius: '8px',
    borderLeft: '4px solid #818cf8',
    fontSize: '14px',
    lineHeight: '1.5',
    color: '#cbd5e1',
  },
};